### ISSUE TITLE
Infografía de Librerías

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/infografia-de-las-librerias-Anthony4523#2]
![Librerías](https://user-images.githubusercontent.com/73609728/115189344-efebec80-a0ab-11eb-8669-c91b9281fa30.png)

**Comment by IsraelNicolas61** [comment]
Calificación: 18

Calificó: Israel Nicolás, Uzías López

**Comment by josealfredo79** [comment]
Bien hecho y revisado.
